---
title: "Report Template for CGR Telomere Analysis"
output: html_document
params:
  input.path: ""
  output.path: ""
  project.id: ""
  plate.content.report: ""
  plate.list: ""
  final.tsv: ""
  infer.384.locations: FALSE
  subject.list.from.input.path: TRUE
---

---
# Make sure required output directory structure exists
---

```{r create.output.directories, eval=TRUE, echo=FALSE}
## if output directory path does not exist, create it
create.output.directories(output.path)
```


---
# Detect input files based on fixed input directory structure
---

```{r find.input.files, eval=TRUE, echo=FALSE}
## aggregate pairs of filenames from input.path/Data/Exports
input.files <- find.input.files(paste(input.path, "Data",
  "Exports",
  sep = "/"
))
```


---
# Load data from detected input files
---

```{r load.exported.data, eval=TRUE, echo=FALSE}
## load data from acquired pairs of files
input.data <- lapply(input.files, function(i) {
  read.export.datum(i,
    source.search.path = paste(input.path,
      "Data",
      "Analysis",
      sep = "/"
    ),
    subject.list.from.input.path = subject.list.from.input.path,
    plate.content.report = plate.content.report,
    plate.list = plate.list
  )
})
```

---
# Run primary analysis generation on loaded data
---

```{r run.primary.analysis, eval=TRUE, echo=FALSE}
## run primary analysis steps for Data/Analysis
primary.analysis <- lapply(input.data, function(i) {
  create.analysis(i,
    plate.content.report = plate.content.report,
    plate.list = plate.list,
    infer.384.locations = infer.384.locations
  )
})
```

---
# Report primary analysis results to file
---

```{r report.primary.analysis, eval=TRUE, echo=FALSE}
## report the primary analysis results to the output/Data/Analysis
lapply(primary.analysis, function(i) {
  report.primary.analysis(i, output.path, project.id)
})
```

---
# Report final summary table
---
```{r report.final.table, eval=TRUE, echo=FALSE}
## report the final summary table of combined data across primary analyses
res <- rbind()
for (i in 1:length(primary.analysis)) {
  res <- rbind(
    res,
    format.final.analysis(
      primary.analysis[[i]],
      project.id
    )
  )
}
write.table(res,
  final.tsv,
  row.names = FALSE,
  col.names = TRUE,
  quote = FALSE,
  sep = "\t"
)
```

---
# Placeholder final block, to report run success
---

```{r, eval=TRUE, echo=FALSE}
print("all done for now")
```
